### ISSUE TITLE
[BUG]: An unexpected error has occurred: block timestamp is too old upon restart 

### ISSUE THREAD

**Issue by motoeng** [koinos/koinos-state-db-cpp#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Syncing new node with latest version of docker and docker compose.
after cloning the repo, i use git checkout v0.4.1. The koinos env file self populates with the following information:

MEMPOOL_TAG=v0.4.1
CHAIN_TAG=v0.4.2
BLOCK_STORE_TAG=v0.4.2
P2P_TAG=v0.4.2
BLOCK_PRODUCER_TAG=v0.4.2
TRANSACTION_STORE_TAG=v0.4.3
CONTRACT_META_STORE_TAG=v0.4.3
JSONRPC_TAG=v0.4.2

Node is syncing and suddenly stops. I gracefully shutdown and restart the node and it fails to sync due to fatal error.

logs attached
[block_store.log](https://github.com/koinos/koinos/files/9795990/block_store.log)
[000.log](https://github.com/koinos/koinos/files/9795994/000.log)
[transaction_store.log](https://github.com/koinos/koinos/files/9795996/transaction_store.log)
[000.log](https://github.com/koinos/koinos/files/9795997/000.log)
[000.log](https://github.com/koinos/koinos/files/9795999/000.log)

### Environment

```markdown
- OS:
Ubuntu 18.04
Docker version 20.10.19, build d85ef84
Docker Compose version v2.11.2
```

**Comment by mvandeberg** [comment]
This specific bug is because the rocksdb backend only writes metadata out to disk on shut down. When the node does not shut down cleanly, the metadata is not there, so when the node starts back up, the metadata and chain state are desynced.

**Comment by mvandeberg** [comment]
Possibly related to koinos/koinos#48

We believe this error occurs after unclean shutdown if the node was started after genesis and the other error is if the node was started from genesis. In either case, writing metadata on every commit should prevent the problem and allow full node recovery on most unclean shutdowns.
