### ISSUE TITLE
Merge iterator refactor

### ISSUE THREAD

**Issue by theoreticalbts** [koinos/koinos-state-db-cpp#6]
I started writing this as a comment to PR koinos/koinos-chain#108, but it's a large enough redesign that I decided to create its own issue.

This issue is non-urgent, to the extent it's optimization of the internal implementation of `statedb`.

However I do also propose a couple possible changes to `statedb` "upward-facing" API, and corresponding syscalls (smart contract "downward-facing" API), so we should decide if those are desirable.

In PR koinos/koinos-chain#108, we have a simple algorithm for `++`.  The algorithm for `--` looks much more complicated.  It seems like these algorithms ought to be totally symmetrical.  Especially since we're willing to have a `by_reverse_order_revision` index which, AFAICT, exists solely to support `--`.

Why aren't they symmetrical?

I think it has to do with lookahead.  For the forward direction, we peek one element ahead when we initialize the `iter_revision_index` container.  Then "peek 1 ahead" is always just the first element of the container, and we update the container to maintain this invariant.

For backward iteration, we do the same thing, but the peeking code is all located in the `operator--` method, since we haven't defined a container with this pre-computed.

Basically in order to support bi-directional iterators that can be either incremented or decremented, we don't need one container with two indexes.  Instead we need two containers:  One to support forward iteration, another to support backward iteration.

Some other questions:

- Do we need an iterator that supports both backward and forward iteration?  Seems like most application logic would only want to iterate in one direction.
- If the caller knows it will only be advancing one element, we could avoid the container altogether.  Instead of "peek at each sub-iterator, put the elements in container, return the first element of container, destruct container" you do "peek at each sub-iterator, keep track of the minimum, return the minimum".
- Do we want to add iterators to the `statedb` API?  Then code can use the iterators to do iteration efficiently (e.g. saving state).
- Do we want to add iterators to the VM API?  Then smart contract code can use the iterators to do iteration efficiently.

**Comment by mvandeberg** [comment]
Should be handled in #5
